#!/bin/bash

path=$(dirname "${BASH_SOURCE[0]}")
if [ -d "${path}/.git" ]; then
    python3 "${path}/src/Porthole.py" "$@"
else
    python3 "${path}/../lib/python3.6/site-packages/Porthole/Porthole.py" "$@"
fi

